# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.10

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - react-pwa-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - react-pwa-dependencies-

      - run: yarn install

      # Update cache
      - save_cache:
          paths:
            - node_modules
          key: react-pwa-dependencies-{{ checksum "package.json" }}

      # Run tests
      #- run: yarn test

  build-deploy:
    machine: true
    steps:
      - checkout

      # Build the Docker container
      - run: |
          docker build -t react-pwa:latest .

      # Push the built containers to AWS ECR
      - run: |
          eval $(aws ecr get-login --no-include-email --region us-east-1)
          docker tag react-pwa:latest 711655675495.dkr.ecr.us-east-1.amazonaws.com/react-pwa:latest
          docker push 711655675495.dkr.ecr.us-east-1.amazonaws.com/react-pwa:latest

workflows:
  version: 2
  install-build-deploy:
    jobs:
      - build
      - build-deploy:
          requires:
            - build
